import type { ComponentMeta } from "@jabkit/build-registry";

export default {
  name: "admit-one-ticket",
  displayName: "AdmitOneTicket",
  version: "1.1.0",
  addedAt: "2026-09-15",
  description:
    "Notched event ticket with a perforated admit-one stub, dithered stock, pointer tilt, and a glare that tracks the pointer.",
  sectionCategory: "content",
  purpose:
    "Puts a physical door pass on an event landing so visitors can read presenter, guest, venue, and stub copy at ticket proportions.",
  bestFor: [
    "concert and festival landings",
    "conference or school-day announcements",
    "limited-entry drops that need a memorable pass",
  ],
  avoidFor: [
    "booking confirmation with payment ledgers",
    "dense calendars of many shows",
    "task-heavy product UI where pointer tilt would compete with controls",
  ],
  tone: ["playful", "confident", "experimental"],
  industries: ["events", "media", "entertainment"],
  contentDensity: "low",
  visualWeight: "high",
  layout: {
    type: "card",
    alignment: "center",
    columns: 1,
  },
  slots: [
    "presenter",
    "event",
    "attendee",
    "venue",
    "dates",
    "stub",
    "watermark",
  ],
  capabilities: {
    supportsImage: false,
    supportsVideo: false,
    supportsForm: false,
    supportsCTA: false,
    supportsDarkMode: true,
  },
  recommendedAfter: ["hero", "logos"],
  recommendedBefore: ["pricing", "cta", "faq"],
  tags: [
    "ticket",
    "admit-one",
    "event",
    "dither",
    "stub",
    "tilt",
    "glare",
    "marketing",
    "landing",
  ],
  dependencies: [],
  registryDependencies: [],
  a11y: { keyboardNav: false, reducedMotion: true },
  preview: { layout: "fit", width: 1440, height: 900 },
} satisfies ComponentMeta;
