import type { TrackerCardProps } from "./TrackerCard.types";

export const trackerCardMocks = {
  default: {
    eyebrow: "Live shipment",
    heading: "Your parcel is on the water.",
    description:
      "A waybill card for Harbor Atelier, with route, checkpoints, and a scan mark shoppers can keep on their phone.",
    status: "in-transit",
    statusLabel: "In transit",
    statusDetail: "Left Lisbon atelier. Next scan at Harbor District.",
    trackingLabel: "Tracking",
    trackingNumber: "HA 20418 991 LIS",
    copyLabel: "Copy",
    copiedLabel: "Copied",
    courierLabel: "Courier",
    courier: "Northline Freight",
    etaLabel: "Arrives",
    eta: "Wed 23 Sep",
    originLabel: "From",
    destinationLabel: "To",
    origin: {
      city: "Lisbon",
      region: "Atelier yard",
      code: "LIS",
    },
    destination: {
      city: "New York",
      region: "Harbor District",
      code: "HDN",
    },
    stepsHeading: "Checkpoints",
    steps: [
      {
        id: "packed",
        label: "Packed at atelier",
        time: "Fri 19 Sep, 14:20",
        complete: true,
      },
      {
        id: "cleared",
        label: "Cleared Lisbon dock",
        time: "Sat 20 Sep, 08:05",
        complete: true,
      },
      {
        id: "sea",
        label: "On the Atlantic crossing",
        time: "Mon 22 Sep, 06:40",
        complete: true,
        current: true,
      },
      {
        id: "harbor",
        label: "Harbor District inbound",
        time: "Expected Tue 23 Sep",
      },
      {
        id: "door",
        label: "Out for delivery",
        time: "Expected Wed 23 Sep",
      },
    ],
    scanLabel: "Scan at pickup",
    showScan: true,
    primaryAction: { label: "Open full track", href: "#track" },
    secondaryAction: { label: "View order", href: "#order" },
  },
  alternate: {
    eyebrow: "Same-day drop",
    heading: "Out for the last mile.",
    description:
      "A compact tracker for a gift jacket heading to Halden Quay, with the courier already on the dock road.",
    status: "out-for-delivery",
    statusLabel: "Out for delivery",
    statusDetail: "Mira has the parcel. Window is 16:00 to 18:00.",
    trackingLabel: "Tracking",
    trackingNumber: "HA G 7712 HDN",
    copyLabel: "Copy",
    copiedLabel: "Copied",
    courierLabel: "Courier",
    courier: "Dock Runner 4",
    etaLabel: "Window",
    eta: "Today, 16:00-18:00",
    originLabel: "From",
    destinationLabel: "To",
    origin: {
      city: "Harbor District",
      region: "Sort hub",
      code: "HDN",
    },
    destination: {
      city: "Halden Quay",
      region: "Dock 2, hold for pickup",
      code: "HQ2",
    },
    stepsHeading: "Checkpoints",
    steps: [
      {
        id: "hub",
        label: "Sorted at Harbor hub",
        time: "Today, 09:12",
        complete: true,
      },
      {
        id: "loaded",
        label: "Loaded onto Dock Runner 4",
        time: "Today, 14:48",
        complete: true,
      },
      {
        id: "route",
        label: "On the quay road",
        time: "Today, 15:21",
        complete: true,
        current: true,
      },
      {
        id: "ready",
        label: "Ready at Dock 2",
        time: "Expected 16:10",
      },
    ],
    scanLabel: "Show at Dock 2",
    showScan: true,
    primaryAction: { label: "Share pickup code", href: "#share" },
    secondaryAction: { label: "Change window", href: "#window" },
  },
} satisfies Record<"default" | "alternate", TrackerCardProps>;
