import type { ComponentMeta } from "@jabkit/build-registry";

export default {
  name: "ride-booking-form",
  displayName: "RideBookingForm",
  version: "1.1.0",
  addedAt: "2026-09-15",
  description:
    "Two-column mobility booking block with a city line, oversized headline, connected pickup and dropoff fields, Today and Now chips, and a price CTA.",
  sectionCategory: "form",
  purpose:
    "Lets a ride-hailing landing page collect pickup, dropoff, and a departure window beside a city illustration.",
  bestFor: [
    "taxi and rideshare landing pages",
    "airport transfer campaigns",
    "scheduled fleet booking",
  ],
  avoidFor: ["multi-step checkout with payment", "live map dispatch consoles"],
  tone: ["clean", "professional", "confident"],
  industries: ["transportation", "travel", "mobility"],
  contentDensity: "medium",
  visualWeight: "high",
  layout: {
    type: "split",
    alignment: "left",
    columns: 2,
  },
  slots: [
    "cityLine",
    "headline",
    "pickupField",
    "dropoffField",
    "dateChip",
    "timeChip",
    "searchCTA",
    "loginLink",
    "cityMedia",
  ],
  capabilities: {
    supportsImage: true,
    supportsVideo: false,
    supportsForm: true,
    supportsCTA: true,
    supportsDarkMode: true,
  },
  recommendedAfter: ["hero", "features"],
  recommendedBefore: ["testimonials", "cta"],
  inspoUrl: "https://21st.dev/@ravikatiyar162/components/ride-booking-form",
  tags: [
    "ride",
    "booking",
    "form",
    "marketing",
    "mobility",
    "taxi",
    "conversion",
  ],
  dependencies: ["lucide-react"],
  registryDependencies: ["button"],
  a11y: { keyboardNav: true, reducedMotion: true },
  preview: { layout: "fit", width: 1440, height: 900 },
} satisfies ComponentMeta;
