import type {
  EventManagerEvent,
  EventManagerProps,
} from "./EventManager.types";

const today = new Date(2026, 8, 6);

const defaultEvents: EventManagerEvent[] = [
  {
    id: "standup",
    title: "Harbor standup",
    description: "Daily blockers and shipping notes for the Northline crew.",
    startTime: new Date(2026, 8, 7, 9, 0),
    endTime: new Date(2026, 8, 7, 9, 25),
    tone: "chart-1",
    category: "Meeting",
    attendees: ["Lina Park", "Omar Wells", "Priya Shah"],
    tags: ["Work", "Team"],
  },
  {
    id: "design-review",
    title: "Cover frame review",
    description: "Walk the Harbor cover frames with product and design.",
    startTime: new Date(2026, 8, 7, 14, 0),
    endTime: new Date(2026, 8, 7, 15, 30),
    tone: "chart-4",
    category: "Meeting",
    attendees: ["Mina Cho", "Ellis Grant"],
    tags: ["Important", "Client"],
  },
  {
    id: "pr-pass",
    title: "Auth PR pass",
    description: "Review recovery-path pull requests before the cut.",
    startTime: new Date(2026, 8, 8, 10, 0),
    endTime: new Date(2026, 8, 8, 11, 0),
    tone: "chart-2",
    category: "Task",
    tags: ["Work", "Urgent"],
  },
  {
    id: "client-readout",
    title: "Q4 readout",
    description: "Share the Harbor roadmap with the Northline stakeholders.",
    startTime: new Date(2026, 8, 9, 15, 0),
    endTime: new Date(2026, 8, 9, 16, 30),
    tone: "chart-3",
    category: "Meeting",
    attendees: ["Jonah Reed", "Asha Cole", "Devon Hale"],
    tags: ["Important", "Client"],
  },
  {
    id: "gym",
    title: "Evening gym",
    description: "Strength block at the dockside studio.",
    startTime: new Date(2026, 8, 7, 18, 0),
    endTime: new Date(2026, 8, 7, 19, 0),
    tone: "chart-5",
    category: "Personal",
    tags: ["Personal"],
  },
  {
    id: "sprint",
    title: "Sprint planning",
    description: "Lock stories and estimates for the next Harbor cut.",
    startTime: new Date(2026, 8, 10, 10, 0),
    endTime: new Date(2026, 8, 10, 12, 0),
    tone: "chart-1",
    category: "Meeting",
    attendees: ["Harbor team"],
    tags: ["Work", "Team", "Important"],
  },
  {
    id: "clinic",
    title: "Clinic visit",
    description: "Annual checkup at Riverside Medical.",
    startTime: new Date(2026, 8, 11, 11, 0),
    endTime: new Date(2026, 8, 11, 12, 0),
    tone: "destructive",
    category: "Personal",
    tags: ["Personal", "Important"],
  },
  {
    id: "deploy",
    title: "Production deploy",
    description: "Ship Harbor 2.5 with the invoice filter and recovery path.",
    startTime: new Date(2026, 8, 11, 16, 0),
    endTime: new Date(2026, 8, 11, 17, 0),
    tone: "chart-2",
    category: "Task",
    tags: ["Work", "Urgent"],
  },
  {
    id: "coffee",
    title: "Coffee with Mina",
    description: "Catch up at the canal cafe after the cover review.",
    startTime: new Date(2026, 8, 12, 15, 0),
    endTime: new Date(2026, 8, 12, 16, 0),
    tone: "chart-5",
    category: "Personal",
    tags: ["Personal"],
  },
  {
    id: "budget",
    title: "Budget review",
    description: "Quarterly spend review with finance.",
    startTime: new Date(2026, 8, 14, 13, 0),
    endTime: new Date(2026, 8, 14, 14, 30),
    tone: "chart-3",
    category: "Meeting",
    attendees: ["Finance"],
    tags: ["Work", "Important"],
  },
];

const alternateEvents: EventManagerEvent[] = [
  {
    id: "invoice-walk",
    title: "Invoice walkthrough",
    description: "Walk unpaid filters with ops before Friday.",
    startTime: new Date(2026, 9, 12, 13, 0),
    endTime: new Date(2026, 9, 12, 14, 0),
    tone: "chart-2",
    category: "Task",
    attendees: ["Ops"],
    tags: ["Work", "Urgent"],
  },
  {
    id: "offsite",
    title: "Northline offsite",
    description: "Half-day workshop at the millhouse.",
    startTime: new Date(2026, 9, 22, 10, 0),
    endTime: new Date(2026, 9, 22, 16, 0),
    tone: "chart-4",
    category: "Meeting",
    attendees: ["Harbor team"],
    tags: ["Team", "Important"],
  },
  {
    id: "reminder",
    title: "Send waitlist notes",
    description: "Reminder to mail confirmation copy.",
    startTime: new Date(2026, 9, 12, 9, 0),
    endTime: new Date(2026, 9, 12, 9, 15),
    tone: "chart-1",
    category: "Reminder",
    tags: ["Work"],
  },
];

const categories = ["Meeting", "Task", "Reminder", "Personal"];
const availableTags = [
  "Important",
  "Urgent",
  "Work",
  "Personal",
  "Team",
  "Client",
];

export const eventManagerMocks = {
  default: {
    title: "Harbor calendar",
    description: "Search, filter, and reschedule the Northline week.",
    defaultEvents,
    categories,
    availableTags,
    defaultView: "month",
    today,
    defaultDate: today,
    searchPlaceholder: "Search events",
    emptyLabel: "No events match these filters.",
    addEventLabel: "New event",
    todayLabel: "Today",
  },
  alternate: {
    title: "October cut",
    description: "A quieter board focused on ops work.",
    defaultEvents: alternateEvents,
    categories,
    availableTags,
    defaultView: "list",
    today,
    defaultDate: new Date(2026, 9, 12),
    defaultSearch: "invoice",
    defaultTagFilter: "Work",
    defaultCategoryFilter: "Task",
    searchPlaceholder: "Filter by title",
    emptyLabel: "Nothing in this slice.",
    addEventLabel: "Add to cut",
    todayLabel: "Jump to today",
  },
} satisfies Record<string, EventManagerProps>;
