import type {
  CarouselCardsItem,
  CarouselCardsProps,
} from "./CarouselCards.types";

const listings: CarouselCardsItem[] = [
  {
    id: "drawing",
    title: "Dawn drawing on the harbor wall",
    image: "/assets/d3f9bde61c9a29e7.webp",
    imageAlt: "Empty office corridor with glass rooms and daylight",
    location: "North Quay, Lisbon",
    price: 48,
    currency: "EUR",
    rating: 4.9,
    reviewCount: 128,
    badge: "Original",
    date: "Closes 21 May",
    href: "#drawing",
  },
  {
    id: "studio",
    title: "Half-day desk in the plant room",
    image: "/assets/462c849dc9a41e59.webp",
    imageAlt: "Sunlit studio desks with plants and open notebooks",
    location: "Campo de Ourique",
    price: 72,
    currency: "EUR",
    rating: 4.8,
    reviewCount: 86,
    badge: "Popular",
    date: "Open Saturdays",
    href: "#studio",
  },
  {
    id: "lamp",
    title: "Evening light study with an arc lamp",
    image: "/assets/6cc11e462a9aaded.webp",
    imageAlt: "Arc floor lamp lighting a quiet corner",
    location: "Estrela atelier",
    price: 36,
    currency: "EUR",
    rating: 4.7,
    reviewCount: 54,
    date: "Closes 4 Jun",
    href: "#lamp",
  },
  {
    id: "concrete",
    title: "Concrete stair walk with a guide",
    image: "/assets/97c532d558fa4fbc.webp",
    imageAlt: "Concrete structure photographed from the ground",
    location: "Alcântara yards",
    price: 55,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 41,
    badge: "New",
    date: "Fridays only",
    href: "#concrete",
  },
  {
    id: "lounge",
    title: "Oak lounge hour and a slow pour",
    image: "/assets/462a1be29787cd8e.webp",
    imageAlt: "Low oak lounge chair on a pale floor",
    location: "Príncipe Real",
    price: 29,
    currency: "EUR",
    rating: 4.9,
    reviewCount: 203,
    badge: "Quiet",
    date: "Drop-in",
    href: "#lounge",
  },
  {
    id: "stone",
    title: "Stone table still-life session",
    image: "/assets/488fa5330da1224c.webp",
    imageAlt: "Sculptural stone side table in a sunlit room",
    location: "Mouraria studio",
    price: 64,
    currency: "EUR",
    rating: 4.8,
    reviewCount: 67,
    date: "Closes 12 Jun",
    href: "#stone",
  },
];

const workshops: CarouselCardsItem[] = [
  {
    id: "daybed",
    title: "Linen daybed reading room",
    image: "/assets/7cb36691e11ed9af.webp",
    imageAlt: "Linen daybed against a plaster wall",
    location: "Graça house",
    price: 42,
    currency: "USD",
    rating: 5,
    reviewCount: 19,
    badge: "Members",
    date: "Sundays",
    href: "#daybed",
    favorited: true,
  },
  {
    id: "pendant",
    title: "Throw a pendant, keep the first one",
    image: "/assets/4f6410f5452c0ba5.webp",
    imageAlt: "Hand-thrown ceramic pendant light",
    location: "Intendente kiln",
    price: 110,
    currency: "USD",
    rating: 4.9,
    reviewCount: 33,
    badge: "Sold out soon",
    date: "Closes 18 Jun",
    href: "#pendant",
  },
  {
    id: "harbor",
    title: "Night containers along the dock",
    image: "/assets/d7eddb427ba6f203.webp",
    imageAlt: "Shipping containers stacked along a lit harbor dock",
    location: "Santa Apolónia",
    price: 38,
    currency: "USD",
    rating: 4.5,
    reviewCount: 91,
    date: "Twilight slot",
    href: "#harbor",
  },
  {
    id: "lab",
    title: "Lab desk with a borrowed machine",
    image: "/assets/4cc437eeea3384d1.webp",
    imageAlt: "Researcher reviewing data on a laptop in a bright lab",
    location: "Ajuda campus",
    price: 88,
    currency: "USD",
    rating: 4.7,
    reviewCount: 22,
    badge: "Limited",
    date: "Weekdays",
    href: "#lab",
  },
];

export const carouselCardsMocks = {
  default: {
    eyebrow: "In the city this month",
    heading: "Experiences worth a slow afternoon",
    description:
      "Book a desk, a walk, or a table. Cards snap as you scroll; save the ones you want to keep.",
    viewAllHref: "#all-experiences",
    viewAllLabel: "Show all",
    items: listings,
  },
  alternate: {
    eyebrow: "Member workshops",
    heading: "Rooms you can book by the hour",
    description:
      "A tighter set of listings with dollar prices and a pre-saved favorite.",
    viewAllHref: "#workshops",
    viewAllLabel: "Browse workshops",
    items: workshops,
  },
} satisfies Record<"default" | "alternate", CarouselCardsProps>;
