import type { ComponentMeta } from "@jabkit/build-registry";

export default {
  name: "application-shell13",
  displayName: "ApplicationShell13",
  version: "1.0.0",
  addedAt: "2026-09-05",
  description:
    "Top navigation dashboard shell with search, org and user menus, dropdown nav groups, a mobile drawer, and a bottom bar.",
  sectionCategory: "application-shell",
  purpose:
    "Frames a responsive business application with global search, organization controls, and adaptive navigation.",
  bestFor: [
    "multi-page SaaS products",
    "administration tools",
    "business dashboards",
  ],
  avoidFor: ["single-purpose forms", "marketing landing pages"],
  tone: ["professional", "structured", "technical"],
  industries: ["SaaS", "enterprise software"],
  contentDensity: "high",
  visualWeight: "high",
  layout: {
    type: "stack",
    alignment: "left",
  },
  slots: [
    "brand",
    "topNavigation",
    "search",
    "organizationMenu",
    "accountMenu",
    "mobileNavigation",
    "pageContent",
  ],
  capabilities: {
    supportsImage: false,
    supportsVideo: false,
    supportsForm: false,
    supportsCTA: false,
    supportsDarkMode: true,
  },
  tags: [
    "dashboard",
    "application-shell",
    "navigation",
    "header",
    "dropdown",
    "search",
    "organization",
    "mobile",
  ],
  dependencies: [],
  registryDependencies: [
    "avatar",
    "badge",
    "button",
    "dialog",
    "dropdown-menu",
    "input",
    "separator",
  ],
  a11y: { keyboardNav: true, reducedMotion: true },
  preview: { layout: "fit", width: 1440, height: 900 },
} satisfies ComponentMeta;
