import type { PortfolioDashboardProps } from "./PortfolioDashboard.types";

const defaultNavGroups: NonNullable<PortfolioDashboardProps["navGroups"]> = [
  {
    label: "WORKSPACE",
    items: [
      { id: "overview", label: "Overview", icon: "overview" },
      {
        id: "policy-threads",
        label: "Policy Threads",
        icon: "threads",
        count: "123",
      },
      {
        id: "documents",
        label: "Documents",
        icon: "documents",
        count: "3,154",
      },
      { id: "claims-hub", label: "Claims Hub", icon: "claims" },
      { id: "renewals", label: "Renewals", icon: "renewals" },
    ],
  },
  {
    label: "TEAM",
    items: [
      { id: "clients", label: "Clients", icon: "clients" },
      {
        id: "shared-portfolio",
        label: "Shared Portfolio",
        icon: "shared",
      },
    ],
  },
  {
    label: "CONFIGURE",
    items: [
      { id: "integrations", label: "Integrations", icon: "integrations" },
      { id: "settings", label: "Settings", icon: "settings" },
    ],
  },
];

export const portfolioDashboardMocks = {
  default: {
    brand: "Harborline",
    greeting: "Good Morning, Vansh",
    searchPlaceholder: "find a control",
    policyCountLabel: "View all 1235",
    user: {
      name: "Vansh Patel",
      email: "vansh@harborline.co",
      initials: "VP",
      image: "/assets/2d2e13918d75791c.webp",
      role: "Broker",
    },
    navGroups: defaultNavGroups,
    alerts: [
      { id: "renewals", label: "3 renewals due this week", tone: "muted" },
      {
        id: "claims",
        label: "2 claims require your review",
        tone: "warning",
      },
    ],
    stats: [
      {
        id: "active",
        label: "Active policies",
        value: "147,392",
        delta: "23",
        period: "this month",
        trend: "up",
        bars: [8, 10, 9, 13, 12, 15, 18, 22, 28, 35],
      },
      {
        id: "premiums",
        label: "Premiums Collected",
        value: "$94.2K",
        delta: "8.4%",
        period: "vs last month",
        trend: "up",
        bars: [9, 14, 18, 17, 14, 16, 22, 21, 28, 35],
      },
      {
        id: "claims",
        label: "Open Claims",
        value: "17",
        delta: "4",
        period: "this week",
        trend: "down",
        bars: [14, 11, 9, 12, 10, 15, 28, 13, 20, 18],
      },
      {
        id: "retention",
        label: "Retention Rate",
        value: "91%",
        delta: "Stable",
        period: "",
        trend: "stable",
        bars: [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
      },
    ],
    policies: [
      {
        id: "hc-liability",
        initials: "HC",
        name: "Henderson Corp",
        type: "Commercial Liability",
        status: "Active",
        tone: "success",
        price: "$12,400/yr",
        detail: "Due: Apr 28",
      },
      {
        id: "pr-vehicle",
        initials: "PR",
        name: "Priya Rajan",
        type: "Vehicle Insurance",
        status: "Claim",
        tone: "primary",
        price: "$2,100/yr",
        detail: "Claim open",
      },
      {
        id: "ds-property",
        initials: "DS",
        name: "Del Sol Properties",
        type: "Properties & contents",
        status: "Review",
        tone: "warning",
        price: "$8,750/yr",
        detail: "Risk Flagged",
      },
      {
        id: "ma-do",
        initials: "MA",
        name: "Malik & Associates",
        type: "Directors & Officers",
        status: "Pending",
        tone: "warning",
        price: "$6,200/yr",
        detail: "Renewal draft",
      },
      {
        id: "gr-contents",
        initials: "GR",
        name: "Greenfield Retail",
        type: "Contents cover",
        status: "Active",
        tone: "success",
        price: "$2,100/yr",
        detail: "Due: Jul 26",
      },
      {
        id: "nb-life",
        initials: "NB",
        name: "N Bergstrom",
        type: "Lifetime policy",
        status: "Lapsed",
        tone: "destructive",
        price: "Due: Apr 28",
        detail: "Follow-up needed",
      },
    ],
    insights: [
      {
        id: "henderson",
        body: "Henderson Corp renewal due in 4 days. Del Sol property risk score elevated, 3 open claims correlate with weather events. 2 policies lapsing this month if no action taken.",
      },
      {
        id: "pinnacle",
        body: "Pinnacle Group upcoming audit in 10 days. Coastal region risk factors increasing, 4 claims associated with flooding incidents. 3 policies need renewal confirmation this quarter.",
      },
    ],
    activities: [
      {
        id: "a1",
        time: "Today - 8:42",
        title: "Henderson Corp renewed automatically",
        detail: "AI processed commercial liability renewal",
      },
      {
        id: "a2",
        time: "Yesterday",
        title: "Priya Rajan filed vehicle claim CLM-0291",
        detail: "Damage estimate: $3,200. AI summary ready",
      },
      {
        id: "a3",
        time: "Yesterday",
        title: "Del Sol risk score increased +12%",
        detail: "Review before renewal recommended",
      },
      {
        id: "a4",
        time: "Yesterday",
        title: "Malik & Assoc. renewal draft generated",
        detail: "Awaiting client approval",
      },
    ],
    renewals: [
      {
        id: "r1",
        initials: "GR",
        name: "Greenfield Retail",
        type: "Contents cover",
        due: "4 days",
        tone: "destructive",
      },
      {
        id: "r2",
        initials: "MA",
        name: "Malik & Assoc.",
        type: "Directors & Officers",
        due: "12 days",
        tone: "warning",
      },
      {
        id: "r3",
        initials: "DS",
        name: "Del Sol Properties",
        type: "Property & contents",
        due: "12 days",
        tone: "warning",
      },
      {
        id: "r4",
        initials: "HC",
        name: "Henderson Corp",
        type: "Commercial Liability",
        due: "31 days",
        tone: "primary",
      },
    ],
    riskRows: [
      {
        id: "property",
        label: "Property",
        bars: 12,
        score: 72,
        tone: "destructive",
      },
      { id: "vehicle", label: "Vehicle", bars: 8, score: 54, tone: "primary" },
      {
        id: "liability",
        label: "Liability",
        bars: 9,
        score: 61,
        tone: "warning",
      },
      {
        id: "life",
        label: "Life & health",
        bars: 3,
        score: 28,
        tone: "success",
      },
    ],
    notifications: [
      {
        id: "n1",
        title: "Policy renewal due",
        detail: "Henderson Corp commercial liability expires in 2 days.",
        time: "2 hours ago",
      },
      {
        id: "n2",
        title: "New claim filed",
        detail: "Priya Rajan filed a vehicle claim for roadside damage.",
        time: "5 hours ago",
      },
      {
        id: "n3",
        title: "System update",
        detail: "Scheduled maintenance tonight at 2 AM Eastern.",
        time: "1 day ago",
      },
    ],
    threads: [
      {
        id: "t1",
        title: "Henderson Corp renewal pack",
        client: "Henderson Corp",
        preview: "Please confirm the liability schedule before Friday.",
        updated: "12m",
        unread: 3,
      },
      {
        id: "t2",
        title: "CLM-0291 vehicle photos",
        client: "Priya Rajan",
        preview: "Adjuster notes are attached to the claim thread.",
        updated: "1h",
        unread: 1,
      },
      {
        id: "t3",
        title: "Del Sol flood riders",
        client: "Del Sol Properties",
        preview: "Risk desk flagged coastal exposure for Q2.",
        updated: "Yesterday",
        unread: 0,
      },
    ],
    documents: [
      {
        id: "d1",
        name: "Henderson-liability-2026.pdf",
        kind: "Policy pack",
        owner: "Vansh Patel",
        updated: "Apr 11",
      },
      {
        id: "d2",
        name: "CLM-0291-estimate.xlsx",
        kind: "Claim file",
        owner: "Priya Rajan",
        updated: "Apr 10",
      },
      {
        id: "d3",
        name: "Del-Sol-survey.pdf",
        kind: "Survey",
        owner: "Risk desk",
        updated: "Apr 8",
      },
    ],
    claims: [
      {
        id: "c1",
        reference: "CLM-0291",
        client: "Priya Rajan",
        type: "Vehicle",
        amount: "$3,200",
        status: "Review",
        tone: "warning",
      },
      {
        id: "c2",
        reference: "CLM-0288",
        client: "Del Sol Properties",
        type: "Property",
        amount: "$18,400",
        status: "Open",
        tone: "destructive",
      },
      {
        id: "c3",
        reference: "CLM-0274",
        client: "Greenfield Retail",
        type: "Contents",
        amount: "$940",
        status: "Settled",
        tone: "success",
      },
    ],
    clients: [
      {
        id: "cl1",
        initials: "HC",
        name: "Henderson Corp",
        book: "Commercial",
        policies: 6,
      },
      {
        id: "cl2",
        initials: "PR",
        name: "Priya Rajan",
        book: "Personal",
        policies: 2,
      },
      {
        id: "cl3",
        initials: "MA",
        name: "Malik & Associates",
        book: "Specialty",
        policies: 4,
      },
    ],
    integrations: [
      { id: "i1", name: "Carrier portal", status: "Live", connected: true },
      { id: "i2", name: "Claims intake", status: "Live", connected: true },
      { id: "i3", name: "Accounting sync", status: "Paused", connected: false },
    ],
    usage: {
      label: "Policy queries today",
      current: 714,
      limit: 1000,
      filled: 16,
      total: 30,
    },
  } satisfies PortfolioDashboardProps,
  alternate: {
    brand: "Northglass",
    greeting: "Good Afternoon, Rina",
    searchPlaceholder: "Search policies, claims, clients",
    policyCountLabel: "View all 418",
    initialPage: "claims-hub",
    user: {
      name: "Rina Okonkwo",
      email: "rina@northglass.broker",
      initials: "RO",
      role: "Claims lead",
    },
    navGroups: defaultNavGroups,
    alerts: [
      { id: "renewals", label: "1 renewal due tomorrow", tone: "muted" },
      {
        id: "claims",
        label: "5 claims in desk review",
        tone: "warning",
      },
    ],
    stats: [
      {
        id: "active",
        label: "Active policies",
        value: "18,640",
        delta: "11",
        period: "this month",
        trend: "up",
        bars: [6, 7, 8, 9, 11, 10, 12, 14, 16, 19],
      },
      {
        id: "premiums",
        label: "Premiums Collected",
        value: "$41.8K",
        delta: "2.1%",
        period: "vs last month",
        trend: "down",
        bars: [22, 20, 18, 19, 16, 15, 14, 13, 12, 11],
      },
      {
        id: "claims",
        label: "Open Claims",
        value: "29",
        delta: "6",
        period: "this week",
        trend: "up",
        bars: [8, 9, 10, 12, 11, 14, 16, 18, 20, 22],
      },
      {
        id: "retention",
        label: "Retention Rate",
        value: "87%",
        delta: "Watch",
        period: "",
        trend: "stable",
        bars: [24, 24, 23, 24, 24, 23, 24, 24, 24, 24],
      },
    ],
    policies: [
      {
        id: "ok-fleet",
        initials: "OK",
        name: "Okonkwo Fleet",
        type: "Commercial Motor",
        status: "Active",
        tone: "success",
        price: "$19,800/yr",
        detail: "Due: May 3",
      },
      {
        id: "lt-cargo",
        initials: "LT",
        name: "Lumen Transit",
        type: "Cargo cover",
        status: "Claim",
        tone: "destructive",
        price: "$7,450/yr",
        detail: "Adjuster assigned",
      },
    ],
    insights: [
      {
        id: "fleet",
        body: "Okonkwo Fleet has two vehicles still missing proof of inspection. Cargo claim LT-118 is waiting on a warehouse report.",
      },
    ],
    activities: [
      {
        id: "a1",
        time: "Today - 13:10",
        title: "Lumen Transit claim escalated",
        detail: "Loss adjuster requested warehouse CCTV",
      },
    ],
    renewals: [
      {
        id: "r1",
        initials: "OK",
        name: "Okonkwo Fleet",
        type: "Commercial Motor",
        due: "2 days",
        tone: "destructive",
      },
    ],
    riskRows: [
      { id: "motor", label: "Motor", bars: 14, score: 81, tone: "destructive" },
      { id: "cargo", label: "Cargo", bars: 7, score: 49, tone: "warning" },
    ],
    notifications: [
      {
        id: "n1",
        title: "Adjuster update",
        detail: "Lumen Transit warehouse report is still outstanding.",
        time: "18 minutes ago",
      },
    ],
    threads: [
      {
        id: "t1",
        title: "LT-118 cargo loss",
        client: "Lumen Transit",
        preview: "Need the warehouse CCTV clip from Tuesday night.",
        updated: "18m",
        unread: 4,
      },
    ],
    documents: [
      {
        id: "d1",
        name: "LT-118-notice.pdf",
        kind: "Claim file",
        owner: "Rina Okonkwo",
        updated: "Today",
      },
    ],
    claims: [
      {
        id: "c1",
        reference: "LT-118",
        client: "Lumen Transit",
        type: "Cargo",
        amount: "$26,150",
        status: "Escalated",
        tone: "destructive",
      },
      {
        id: "c2",
        reference: "OK-044",
        client: "Okonkwo Fleet",
        type: "Motor",
        amount: "$1,180",
        status: "Review",
        tone: "warning",
      },
    ],
    clients: [
      {
        id: "cl1",
        initials: "OK",
        name: "Okonkwo Fleet",
        book: "Commercial motor",
        policies: 9,
      },
    ],
    integrations: [
      { id: "i1", name: "Telematics feed", status: "Live", connected: true },
    ],
    usage: {
      label: "Policy queries today",
      current: 212,
      limit: 400,
      filled: 10,
      total: 24,
    },
  } satisfies PortfolioDashboardProps,
} as const;
