import type { ReceiptPricingProps } from "./ReceiptPricing.types";

export const receiptPricingMocks = {
  default: {
    title: "Pricing, printed.",
    description:
      "Every line item, the subtotal, and what you actually owe. Yearly reprints with two months off.",
    merchant: "Meridian",
    merchantNote: "Event analytics for product teams",
    orderPrefix: "MD",
    monthsFree: 2,
    printMs: 460,
    tearMs: 200,
    stagger: 60,
    toothWidth: 12,
    toothDepth: 6,
    grain: 0.05,
    printOnReveal: true,
    showStamp: true,
    showBarcode: true,
    monthlyLabel: "Monthly",
    yearlyLabel: "Yearly",
    currency: "USD",
    locale: "en-US",
    defaultPeriod: "monthly",
    plans: [
      {
        id: "starter",
        name: "Starter",
        tagline: "One developer, one product",
        monthly: 12,
        href: "#starter",
        cta: "Start free trial",
        items: [
          { label: "Seats", value: "1" },
          { label: "Events / mo", value: "100K" },
          { label: "Retention", value: "30 d" },
          { label: "Alerts", value: "5" },
        ],
      },
      {
        id: "team",
        name: "Team",
        tagline: "The whole product team",
        monthly: 32,
        featured: true,
        href: "#team",
        cta: "Start free trial",
        items: [
          { label: "Seats", value: "10" },
          { label: "Events / mo", value: "2M" },
          { label: "Retention", value: "12 mo" },
          { label: "Alerts", value: "Unlimited" },
          { label: "Slack support", value: "Incl." },
        ],
      },
      {
        id: "scale",
        name: "Scale",
        tagline: "Every team in the company",
        monthly: 96,
        href: "#scale",
        cta: "Talk to sales",
        items: [
          { label: "Seats", value: "Unlimited" },
          { label: "Events / mo", value: "25M" },
          { label: "Retention", value: "3 yr" },
          { label: "SSO / SAML", value: "Incl." },
          { label: "Uptime SLA", value: "99.99%" },
        ],
      },
    ],
  },
  alternate: {
    title: "Bindery rates, on a slip.",
    description:
      "Press time, paper, and bind labor listed like a shop ticket. Yearly keeps two months off the tape.",
    merchant: "Halden Bindery",
    merchantNote: "Short-run books and edition work",
    orderPrefix: "HB",
    monthsFree: 2,
    printMs: 460,
    tearMs: 200,
    stagger: 60,
    toothWidth: 12,
    toothDepth: 6,
    grain: 0.05,
    printOnReveal: true,
    showStamp: true,
    showBarcode: true,
    monthlyLabel: "Monthly",
    yearlyLabel: "Yearly",
    currency: "USD",
    locale: "en-US",
    defaultPeriod: "yearly",
    plans: [
      {
        id: "folio",
        name: "Folio",
        tagline: "One press, nights and weekends",
        monthly: 42,
        href: "#folio",
        cta: "Hold Folio",
        items: [
          { label: "Press hours", value: "8" },
          { label: "Text stock", value: "Cream" },
          { label: "Saddle stitch", value: "Incl." },
        ],
      },
      {
        id: "quire",
        name: "Quire",
        tagline: "Weekly editions for a shop",
        monthly: 96,
        featured: true,
        href: "#quire",
        cta: "Hold Quire",
        items: [
          { label: "Press hours", value: "24" },
          { label: "Text stock", value: "Laid" },
          { label: "Case bind", value: "Incl." },
          { label: "Foil stamp", value: "2 hits" },
        ],
      },
    ],
  },
} satisfies Record<"default" | "alternate", ReceiptPricingProps>;
