import type { ReceiptPricingProps } from "./ReceiptPricing.types";

export const receiptPricingMocks = {
  default: {
    title: "Pricing, printed.",
    description:
      "Every line item, the subtotal, and what you actually owe. Yearly reprints with two months off.",
    merchant: "Northslip",
    merchantNote: "Event analytics for product teams",
    orderPrefix: "NS",
    issuedAt: "2026-09-15",
    monthsFree: 2,
    printMs: 460,
    showStamp: true,
    showBarcode: true,
    monthlyLabel: "Monthly",
    yearlyLabel: "Yearly",
    currency: "USD",
    locale: "en-US",
    defaultPeriod: "monthly",
    plans: [
      {
        id: "starter",
        name: "Starter",
        tag: "One builder, one product",
        href: "#starter",
        ctaLabel: "Take Starter",
        monthly: [
          { label: "Builder seat", amount: 19 },
          { label: "Event credits", amount: 12 },
          { label: "Replay window", amount: 4 },
        ],
      },
      {
        id: "studio",
        name: "Studio",
        tag: "A small team shipping weekly",
        href: "#studio",
        ctaLabel: "Take Studio",
        featured: true,
        monthly: [
          { label: "Five seats", amount: 79 },
          { label: "Event credits", amount: 28 },
          { label: "Replay window", amount: 9 },
          { label: "Shared boards", amount: 8 },
        ],
      },
      {
        id: "bench",
        name: "Bench",
        tag: "Org-wide capture and review",
        href: "#bench",
        ctaLabel: "Talk to Bench",
        monthly: [
          { label: "Twenty seats", amount: 220 },
          { label: "Event credits", amount: 64 },
          { label: "Replay window", amount: 18 },
          { label: "Audit export", amount: 22 },
        ],
      },
    ],
  },
  alternate: {
    title: "Bindery rates, on a slip.",
    description:
      "Press time, paper, and bind labor listed like a shop ticket. Yearly keeps two months off the tape.",
    merchant: "Halden Bindery",
    merchantNote: "Short-run books and edition work",
    orderPrefix: "HB",
    issuedAt: "2026-11-03",
    monthsFree: 2,
    printMs: 460,
    showStamp: true,
    showBarcode: true,
    monthlyLabel: "Monthly",
    yearlyLabel: "Yearly",
    currency: "USD",
    locale: "en-US",
    defaultPeriod: "yearly",
    plans: [
      {
        id: "folio",
        name: "Folio",
        tag: "One press, nights and weekends",
        href: "#folio",
        ctaLabel: "Hold Folio",
        monthly: [
          { label: "Press hours", amount: 42 },
          { label: "Text stock", amount: 16 },
          { label: "Saddle stitch", amount: 8 },
        ],
      },
      {
        id: "quire",
        name: "Quire",
        tag: "Weekly editions for a shop",
        href: "#quire",
        ctaLabel: "Hold Quire",
        featured: true,
        monthly: [
          { label: "Press hours", amount: 96 },
          { label: "Text stock", amount: 34 },
          { label: "Case bind", amount: 21 },
          { label: "Foil stamp", amount: 14 },
        ],
      },
    ],
  },
} satisfies Record<"default" | "alternate", ReceiptPricingProps>;
