import type { Team11Props } from "./Team11.types";

export const team11Mocks = {
  default: {
    title: "The people behind the work",
    description:
      "A dense roster for a studio that ships every week. Hover a name on larger screens to read a short bio without the grid shifting.",
    members: [
      {
        src: "/assets/bd48582e630a15fa.webp",
        alt: "Portrait of Amara Cole",
        name: "Amara Cole",
        role: "Design director",
        bio: "Sets the crop, the type, and the argument for leaving a layout alone when it already reads.",
      },
      {
        src: "/assets/2a364f729e4f7c09.webp",
        alt: "Portrait of Julian Hart",
        name: "Julian Hart",
        role: "Product engineer",
        bio: "Builds the parts that have to survive a Thursday ship without a product tour.",
      },
      {
        src: "/assets/d111cc60a8f2bf68.webp",
        alt: "Portrait of Priya Nair",
        name: "Priya Nair",
        role: "Brand lead",
        bio: "Keeps photography, wordmark, and color on the same desk so the page does not get translated twice.",
      },
      {
        src: "/assets/040bd026249d7af9.webp",
        alt: "Portrait of Eli Voss",
        name: "Eli Voss",
        role: "Studio producer",
        bio: "Runs the calendar, the reviews, and the quiet hour before a launch.",
      },
      {
        src: "/assets/45dad0903fef5d02.webp",
        alt: "Portrait of Ines Calder",
        name: "Ines Calder",
        role: "Research lead",
        bio: "Talks to operators, writes the brief in plain language, and cuts anything that needs a legend.",
      },
      {
        src: "/assets/1391b53bc91d2127.webp",
        alt: "Portrait of Rowan Hale",
        name: "Rowan Hale",
        role: "Frontend",
        bio: "Turns tokens and type into pages that still hold together at 375 pixels.",
      },
      {
        src: "/assets/fc2d8371236ac90c.webp",
        alt: "Portrait of Lena Ortiz",
        name: "Lena Ortiz",
        role: "Creative director",
        bio: "Holds the first sentence and the last crop. If either slips, the rest of the page follows.",
      },
      {
        src: "/assets/8c18989537b833e8.webp",
        alt: "Portrait of Malik Adeyemi",
        name: "Malik Adeyemi",
        role: "Engineering",
        bio: "Owns the install path, the registry shape, and the parts that fail loudly instead of quietly.",
      },
      {
        src: "/assets/4132445424a19cc6.webp",
        alt: "Portrait of Hana Iwasaki",
        name: "Hana Iwasaki",
        role: "Art director",
        bio: "Lights portraits, edits color, and refuses stock that looks like a template.",
      },
      {
        src: "/assets/2bd1b12951fdbdb5.webp",
        alt: "Portrait of Owen Briggs",
        name: "Owen Briggs",
        role: "Producer",
        bio: "Keeps print proofs, asset hashes, and Friday handoffs on one list.",
      },
      {
        src: "/assets/8e9489842d5e2cdf.webp",
        alt: "Portrait of Noor Elamin",
        name: "Noor Elamin",
        role: "Ops",
        bio: "Pays vendors, books the table, and notices when a file still has a placeholder name.",
      },
      {
        src: "/assets/9b8fa9955b8bd54f.webp",
        alt: "Portrait of Mira Solano",
        name: "Mira Solano",
        role: "Copy",
        bio: "Writes the line that can survive a quiet room, then cuts the rest.",
      },
    ],
  },
  alternate: {
    title: "Who sits at this table",
    description:
      "Northline is eight people and a long table. On a laptop, hover a cell to open the bio card. On a phone, the list stays flat.",
    highlightedName: "Priya Nair",
    members: [
      {
        src: "/assets/fc2d8371236ac90c.webp",
        alt: "Portrait of Lena Ortiz",
        name: "Lena Ortiz",
        role: "Creative director",
        bio: "Starts every brief with a photograph and a sentence that can be read out loud.",
      },
      {
        src: "/assets/8c18989537b833e8.webp",
        alt: "Portrait of Malik Adeyemi",
        name: "Malik Adeyemi",
        role: "Engineering",
        bio: "Prefers software that does not need a guided tour to make sense.",
      },
      {
        src: "/assets/4132445424a19cc6.webp",
        alt: "Portrait of Hana Iwasaki",
        name: "Hana Iwasaki",
        role: "Art director",
        bio: "Cuts the hero until the product is the brightest thing in the frame.",
      },
      {
        src: "/assets/2bd1b12951fdbdb5.webp",
        alt: "Portrait of Owen Briggs",
        name: "Owen Briggs",
        role: "Producer",
        bio: "Closes the file when the clock says so, even if one more pass would feel nicer.",
      },
      {
        src: "/assets/bd48582e630a15fa.webp",
        alt: "Portrait of Priya Nair",
        name: "Priya Nair",
        role: "Brand lead",
        bio: "Guards the wordmark, the paper stock, and the rule that we do not invent a second accent.",
      },
      {
        src: "/assets/2a364f729e4f7c09.webp",
        alt: "Portrait of Julian Hart",
        name: "Julian Hart",
        role: "Product engineer",
        bio: "Keeps motion on transform and opacity, and off when the system asks for less.",
      },
      {
        src: "/assets/45dad0903fef5d02.webp",
        alt: "Portrait of Ines Calder",
        name: "Ines Calder",
        role: "Research lead",
        bio: "Maps the jobs people actually do, then deletes the features that only look busy.",
      },
      {
        src: "/assets/1391b53bc91d2127.webp",
        alt: "Portrait of Rowan Hale",
        name: "Rowan Hale",
        role: "Frontend",
        bio: "Ships the grid, the hover card, and the small-screen list as one component.",
      },
    ],
  },
} satisfies Record<string, Team11Props>;
