import type { Table2Invoice, Table2Props } from "./Table2.types";

const defaultInvoices: Table2Invoice[] = [
  {
    id: "inv-northline-2408",
    number: "INV-2408",
    customer: "Northline Freight",
    email: "billing@northline.freight",
    amount: 4280,
    paymentMethod: { kind: "card", brand: "Visa", last4: "4242" },
    dueDate: "2026-09-18",
    status: "pending",
  },
  {
    id: "inv-harbor-2407",
    number: "INV-2407",
    customer: "Harbor Studio",
    email: "accounts@harbor.studio",
    amount: 1860.5,
    paymentMethod: { kind: "card", brand: "Mastercard", last4: "5512" },
    dueDate: "2026-09-04",
    status: "overdue",
  },
  {
    id: "inv-kiln-2406",
    number: "INV-2406",
    customer: "Kiln Press",
    email: "pay@kiln.press",
    amount: 940,
    paymentMethod: { kind: "transfer", label: "ACH" },
    dueDate: "2026-08-28",
    status: "paid",
  },
  {
    id: "inv-brine-2405",
    number: "INV-2405",
    customer: "Brine Market",
    email: "finance@brine.market",
    amount: 3125,
    paymentMethod: { kind: "card", brand: "Amex", last4: "1005" },
    dueDate: "2026-09-22",
    status: "pending",
  },
  {
    id: "inv-cedar-2404",
    number: "INV-2404",
    customer: "Cedar Row Labs",
    email: "ops@cedarrow.labs",
    amount: 760,
    paymentMethod: { kind: "card", brand: "Visa", last4: "1881" },
    dueDate: "2026-10-02",
    status: "draft",
  },
  {
    id: "inv-lumen-2403",
    number: "INV-2403",
    customer: "Lumen Archive",
    email: "hello@lumen.archive",
    amount: 2540,
    paymentMethod: { kind: "transfer", label: "Wire" },
    dueDate: "2026-09-11",
    status: "paid",
  },
  {
    id: "inv-silt-2402",
    number: "INV-2402",
    customer: "Silt Cooperative",
    email: "ledger@silt.coop",
    amount: 1188.25,
    paymentMethod: { kind: "card", brand: "Mastercard", last4: "0044" },
    dueDate: "2026-08-30",
    status: "overdue",
  },
  {
    id: "inv-grove-2401",
    number: "INV-2401",
    customer: "Grove Atelier",
    email: "studio@grove.atelier",
    amount: 640,
    paymentMethod: { kind: "card", brand: "Visa", last4: "9910" },
    dueDate: "2026-09-27",
    status: "pending",
  },
  {
    id: "inv-field-2399",
    number: "INV-2399",
    customer: "Field Note Books",
    email: "pay@fieldnote.books",
    amount: 210,
    paymentMethod: { kind: "transfer", label: "ACH" },
    dueDate: "2026-08-12",
    status: "paid",
  },
  {
    id: "inv-oriole-2398",
    number: "INV-2398",
    customer: "Oriole Transit",
    email: "ap@oriole.transit",
    amount: 5790,
    paymentMethod: { kind: "card", brand: "Amex", last4: "3003" },
    dueDate: "2026-09-09",
    status: "overdue",
  },
  {
    id: "inv-quarry-2397",
    number: "INV-2397",
    customer: "Quarry Goods",
    email: "billing@quarry.goods",
    amount: 1475,
    paymentMethod: { kind: "card", brand: "Visa", last4: "2219" },
    dueDate: "2026-10-08",
    status: "draft",
  },
  {
    id: "inv-pine-2396",
    number: "INV-2396",
    customer: "Pine & Copper",
    email: "invoices@pinecopper.shop",
    amount: 890.75,
    paymentMethod: { kind: "card", brand: "Mastercard", last4: "7741" },
    dueDate: "2026-09-15",
    status: "pending",
  },
];

const overdueInvoices: Table2Invoice[] = [
  {
    id: "inv-harbor-2412",
    number: "INV-2412",
    customer: "Harbor Studio",
    email: "accounts@harbor.studio",
    amount: 2640,
    paymentMethod: { kind: "card", brand: "Visa", last4: "4242" },
    dueDate: "2026-08-19",
    status: "overdue",
  },
  {
    id: "inv-silt-2411",
    number: "INV-2411",
    customer: "Silt Cooperative",
    email: "ledger@silt.coop",
    amount: 980,
    paymentMethod: { kind: "transfer", label: "ACH" },
    dueDate: "2026-08-22",
    status: "overdue",
  },
  {
    id: "inv-oriole-2410",
    number: "INV-2410",
    customer: "Oriole Transit",
    email: "ap@oriole.transit",
    amount: 4310,
    paymentMethod: { kind: "card", brand: "Amex", last4: "1005" },
    dueDate: "2026-08-26",
    status: "overdue",
  },
  {
    id: "inv-brine-2409",
    number: "INV-2409",
    customer: "Brine Market",
    email: "finance@brine.market",
    amount: 1550,
    paymentMethod: { kind: "card", brand: "Mastercard", last4: "5512" },
    dueDate: "2026-09-20",
    status: "pending",
  },
];

export const table2Mocks = {
  default: {
    title: "Invoices",
    description: "Search, select, and settle the Northline ledger.",
    searchPlaceholder: "Search invoices",
    emptyLabel: "No invoices match this filter.",
    defaultInvoices,
    pageSize: 6,
  },
  alternate: {
    title: "Past due",
    description: "Reminders and recoveries for Harbor collections.",
    searchPlaceholder: "Filter by customer",
    emptyLabel: "Nothing in this slice.",
    defaultInvoices: overdueInvoices,
    defaultSearch: "Harbor",
    defaultStatusFilter: "overdue",
    pageSize: 4,
  },
} satisfies Record<string, Table2Props>;
