import type { Table2Invoice, Table2Props } from "./Table2.types";

const defaultInvoices: Table2Invoice[] = [
  {
    id: "INV-0041",
    client: "Miriam Okafor",
    initials: "MO",
    project: "Brand Refresh",
    amount: 4200,
    method: "Wire Transfer",
    due: "2026-06-30",
    status: "pending",
  },
  {
    id: "INV-0040",
    client: "Theo Hartmann",
    initials: "TH",
    project: "API Integration",
    amount: 1850,
    method: "Credit Card",
    due: "2026-06-15",
    status: "paid",
  },
  {
    id: "INV-0039",
    client: "Suki Nakamura",
    initials: "SN",
    project: "Dashboard UI",
    amount: 6500,
    method: "ACH",
    due: "2026-06-01",
    status: "overdue",
  },
  {
    id: "INV-0038",
    client: "Elias Ferreira",
    initials: "EF",
    project: "Mobile App MVP",
    amount: 9000,
    method: "Wire Transfer",
    due: "2026-05-28",
    status: "paid",
  },
  {
    id: "INV-0037",
    client: "Priya Menon",
    initials: "PM",
    project: "SEO Audit",
    amount: 780,
    method: "Credit Card",
    due: "2026-05-10",
    status: "refunded",
  },
  {
    id: "INV-0036",
    client: "Dmitri Volkov",
    initials: "DV",
    project: "Data Pipeline",
    amount: 3350,
    method: "ACH",
    due: "2026-04-25",
    status: "paid",
  },
  {
    id: "INV-0035",
    client: "Amara Diallo",
    initials: "AD",
    project: "Design System",
    amount: 5400,
    method: "Wire Transfer",
    due: "2026-06-22",
    status: "pending",
  },
  {
    id: "INV-0034",
    client: "Noah Bergstrom",
    initials: "NB",
    project: "Marketing Site",
    amount: 2100,
    method: "Credit Card",
    due: "2026-04-18",
    status: "paid",
  },
  {
    id: "INV-0033",
    client: "Lucia Romano",
    initials: "LR",
    project: "Onboarding Flow",
    amount: 3950,
    method: "ACH",
    due: "2026-05-31",
    status: "overdue",
  },
  {
    id: "INV-0032",
    client: "Kwame Mensah",
    initials: "KM",
    project: "Analytics Setup",
    amount: 1280,
    method: "Credit Card",
    due: "2026-04-09",
    status: "paid",
  },
  {
    id: "INV-0031",
    client: "Ingrid Larsen",
    initials: "IL",
    project: "Accessibility Pass",
    amount: 2650,
    method: "Wire Transfer",
    due: "2026-06-12",
    status: "pending",
  },
  {
    id: "INV-0030",
    client: "Mateo Castillo",
    initials: "MC",
    project: "Checkout Rebuild",
    amount: 7300,
    method: "ACH",
    due: "2026-03-30",
    status: "refunded",
  },
  {
    id: "INV-0029",
    client: "Yuki Tanaka",
    initials: "YT",
    project: "Email Templates",
    amount: 940,
    method: "Credit Card",
    due: "2026-03-22",
    status: "paid",
  },
  {
    id: "INV-0028",
    client: "Fatima Zahra",
    initials: "FZ",
    project: "Localization",
    amount: 4880,
    method: "Wire Transfer",
    due: "2026-05-19",
    status: "overdue",
  },
  {
    id: "INV-0027",
    client: "Oscar Lindqvist",
    initials: "OL",
    project: "CMS Migration",
    amount: 6150,
    method: "ACH",
    due: "2026-06-05",
    status: "pending",
  },
  {
    id: "INV-0026",
    client: "Hana Novak",
    initials: "HN",
    project: "Component Audit",
    amount: 1720,
    method: "Credit Card",
    due: "2026-03-14",
    status: "paid",
  },
  {
    id: "INV-0025",
    client: "Bilal Haddad",
    initials: "BH",
    project: "Search Revamp",
    amount: 5230,
    method: "Wire Transfer",
    due: "2026-05-02",
    status: "overdue",
  },
  {
    id: "INV-0024",
    client: "Sienna Walsh",
    initials: "SW",
    project: "Pricing Page",
    amount: 1360,
    method: "Credit Card",
    due: "2026-02-26",
    status: "paid",
  },
];

const overdueInvoices: Table2Invoice[] = [
  {
    id: "INV-0039",
    client: "Suki Nakamura",
    initials: "SN",
    project: "Dashboard UI",
    amount: 6500,
    method: "ACH",
    due: "2026-06-01",
    status: "overdue",
  },
  {
    id: "INV-0033",
    client: "Lucia Romano",
    initials: "LR",
    project: "Onboarding Flow",
    amount: 3950,
    method: "ACH",
    due: "2026-05-31",
    status: "overdue",
  },
  {
    id: "INV-0028",
    client: "Fatima Zahra",
    initials: "FZ",
    project: "Localization",
    amount: 4880,
    method: "Wire Transfer",
    due: "2026-05-19",
    status: "overdue",
  },
  {
    id: "INV-0025",
    client: "Bilal Haddad",
    initials: "BH",
    project: "Search Revamp",
    amount: 5230,
    method: "Wire Transfer",
    due: "2026-05-02",
    status: "overdue",
  },
  {
    id: "INV-0041",
    client: "Miriam Okafor",
    initials: "MO",
    project: "Brand Refresh",
    amount: 4200,
    method: "Wire Transfer",
    due: "2026-06-30",
    status: "pending",
  },
];

export const table2Mocks = {
  default: {
    eyebrow: "Acme Inc.",
    title: "Invoices",
    description: "Recent billing activity across all client projects.",
    outstandingLabel: "Outstanding",
    searchPlaceholder: "Filter by client...",
    emptyLabel: "No invoices match your filter.",
    footnote: "Figures shown in USD. Last updated Jun 17, 2026.",
    defaultInvoices,
    pageSize: 7,
    defaultSort: { key: "due", direction: "desc" },
  },
  alternate: {
    eyebrow: "Collections",
    title: "Past due",
    description: "Overdue invoices waiting on a reminder or recovery.",
    outstandingLabel: "Outstanding",
    searchPlaceholder: "Filter by client...",
    emptyLabel: "No invoices match your filter.",
    footnote: "Figures shown in USD. Last updated Jun 17, 2026.",
    defaultInvoices: overdueInvoices,
    defaultSearch: "Suki",
    pageSize: 5,
    defaultSort: { key: "amount", direction: "desc" },
  },
} satisfies Record<string, Table2Props>;
